global_costmap:
   global_frame: map
   robot_base_frame: Dummy_link
   update_frequency: 8.0
   publish_frequency: 8.0
   width: 20.0
   height: 20.0
   resolution: 0.05
   static_map: true
   rolling_window: false
   
   plugins: 
    - {name: static,           type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation,         type: "costmap_2d::InflationLayer"}
